-- ============================================================================
-- Auditable Deep Research Agent - D1 SQLite Schema Migration
-- ============================================================================

-- 1. Research Sessions Table
CREATE TABLE IF NOT EXISTS research_sessions (
    id TEXT PRIMARY KEY,
    query TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'planning', -- planning | searching | synthesizing | auditing | complete | error
    error_message TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME
);

-- 2. Research Plans (Structured Query Decomposition)
CREATE TABLE IF NOT EXISTS research_plans (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES research_sessions(id) ON DELETE CASCADE,
    core_objective TEXT NOT NULL,
    rationale TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 3. Sub-Questions Generated by Planner
CREATE TABLE IF NOT EXISTS sub_questions (
    id TEXT PRIMARY KEY,
    plan_id TEXT NOT NULL REFERENCES research_plans(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL,
    question TEXT NOT NULL,
    search_query TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- pending | searching | completed | failed
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 4. Harvested Source Documents (Full Provenance)
CREATE TABLE IF NOT EXISTS sources (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES research_sessions(id) ON DELETE CASCADE,
    sub_question_id TEXT NOT NULL,
    url TEXT NOT NULL,
    title TEXT NOT NULL,
    domain TEXT,
    raw_content TEXT,
    chunk_count INTEGER DEFAULT 0,
    crawled_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 5. Source Chunks with Vector DB Reference
CREATE TABLE IF NOT EXISTS source_chunks (
    id TEXT PRIMARY KEY,
    source_id TEXT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL,
    sub_question_id TEXT,
    chunk_index INTEGER NOT NULL,
    char_start INTEGER,
    char_end INTEGER,
    content TEXT NOT NULL,
    vector_id TEXT, -- Corresponds to Vectorize ID
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 6. Generated Reports
CREATE TABLE IF NOT EXISTS reports (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES research_sessions(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    executive_summary TEXT NOT NULL,
    body_markdown TEXT NOT NULL,
    confidence_score REAL DEFAULT 0.0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 7. Audited Claims Mapped Back to Vector Sources
CREATE TABLE IF NOT EXISTS report_claims (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES research_sessions(id) ON DELETE CASCADE,
    report_id TEXT REFERENCES reports(id) ON DELETE CASCADE,
    claim_text TEXT NOT NULL,
    source_chunk_ids TEXT NOT NULL, -- JSON array of chunk IDs or source IDs e.g. ["src-1", "src-2"]
    supporting_quote TEXT NOT NULL,
    verification_status TEXT NOT NULL DEFAULT 'verified', -- verified | caution | unsupported
    verification_reasoning TEXT,
    confidence_score REAL DEFAULT 1.0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 8. Step-by-Step Reasoning Trace & Audit Logs
CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL REFERENCES research_sessions(id) ON DELETE CASCADE,
    step TEXT NOT NULL, -- planner | worker | aggregator | synthesizer | auditor | system
    node_name TEXT,
    message TEXT NOT NULL,
    data TEXT, -- JSON payload of structured step state
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for high performance queries
CREATE INDEX IF NOT EXISTS idx_audit_session ON audit_logs(session_id);
CREATE INDEX IF NOT EXISTS idx_sources_session ON sources(session_id);
CREATE INDEX IF NOT EXISTS idx_chunks_source ON source_chunks(source_id);
CREATE INDEX IF NOT EXISTS idx_chunks_session ON source_chunks(session_id);
CREATE INDEX IF NOT EXISTS idx_claims_session ON report_claims(session_id);
CREATE INDEX IF NOT EXISTS idx_subq_session ON sub_questions(session_id);
CREATE INDEX IF NOT EXISTS idx_plans_session ON research_plans(session_id);
CREATE INDEX IF NOT EXISTS idx_reports_session ON reports(session_id);
