import { z } from 'zod';

/**
 * 1. Sub-question generated by the Planner
 */
export const SubQuestionSchema = z.object({
  id: z.string().describe('Unique identifier e.g. subq_1, subq_2'),
  question: z.string().describe('Focused, distinct sub-question to investigate'),
  searchQuery: z.string().describe('Search query keyword string optimized for a web search engine'),
});

export type SubQuestion = z.infer<typeof SubQuestionSchema>;

/**
 * 2. Complete Research Plan decomposed by Planner
 */
export const ResearchPlanSchema = z.object({
  coreObjective: z.string().describe('Precise restatement and scope of the research goal'),
  rationale: z.string().describe('Strategic reasoning explaining why this decomposition ensures exhaustive coverage'),
  subQuestions: z.array(SubQuestionSchema).min(2).max(5).describe('2 to 5 targeted sub-questions for parallel investigation'),
});

export type ResearchPlan = z.infer<typeof ResearchPlanSchema>;

/**
 * 3. Individual Claim Citation Schema
 */
export const ClaimCitationSchema = z.object({
  claimText: z.string().describe('A single concrete, verifiable factual statement or data point asserting a conclusion in the report'),
  sourceChunkIds: z.array(z.string()).describe('Array of source/chunk IDs backing this specific claim, e.g. ["src_1_chunk_0", "src_2_chunk_1"]'),
  supportingQuote: z.string().describe('Exact verbatim quote or concise paraphrase from the cited source chunk that proves this claim'),
});

export type ClaimCitation = z.infer<typeof ClaimCitationSchema>;

/**
 * 4. Synthesized Report Schema generated by Writer
 */
export const SynthesizedReportSchema = z.object({
  title: z.string().describe('Professional, informative research report title'),
  executiveSummary: z.string().describe('Concise high-level executive summary summarizing core findings'),
  bodyMarkdown: z.string().describe('Exhaustive, sectioned research report in clean Markdown formatting, referencing sources inline using [src-X] tags'),
  claims: z.array(ClaimCitationSchema).min(3).describe('Itemized list of all key claims mapped strictly to source chunks and supporting quotes'),
  initialConfidenceScore: z.number().min(0).max(1).describe('Self-assessed evidence confidence score between 0.0 and 1.0'),
});

export type SynthesizedReport = z.infer<typeof SynthesizedReportSchema>;

/**
 * 5. Auditor Single Claim Verification
 */
export const ClaimAuditVerificationSchema = z.object({
  claimText: z.string().describe('The claim being verified'),
  verificationStatus: z.enum(['verified', 'caution', 'unsupported']).describe('Verification outcome: verified (soundly backed), caution (partially supported/extrapolated), unsupported (hallucination or missing evidence)'),
  verificationReasoning: z.string().describe('Auditor reasoning comparing the claim text directly with the retrieved source chunk text'),
  confidenceScore: z.number().min(0).max(1).describe('Confidence score from 0.0 to 1.0 based strictly on source alignment'),
});

export type ClaimAuditVerification = z.infer<typeof ClaimAuditVerificationSchema>;

/**
 * 6. Auditor Overall Verification Result
 */
export const AuditorResultSchema = z.object({
  overallAuditScore: z.number().min(0).max(1).describe('Weighted audit reliability score for the entire report'),
  auditSummary: z.string().describe('Executive audit summary detailing reliability, coverage, and any noted discrepancies'),
  verifiedClaims: z.array(ClaimAuditVerificationSchema).describe('Verification assessment for every evaluated claim'),
});

export type AuditorResult = z.infer<typeof AuditorResultSchema>;

/**
 * 7. Evidence Aggregator Gap Analysis (Iterative Refinement)
 */
export const AggregatorGapAnalysisSchema = z.object({
  isSufficient: z.boolean().describe('True if collected evidence is comprehensive enough to synthesize a complete report, false if critical gaps exist'),
  gapSummary: z.string().describe('Summary of information coverage and any missing critical aspects'),
  followUpQueries: z.array(z.string()).optional().describe('Optional follow-up search queries if critical gaps require additional exploration'),
});

export type AggregatorGapAnalysis = z.infer<typeof AggregatorGapAnalysisSchema>;
